AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  LoggerSampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: LoggerSample.App.handleRequest
      Runtime: java8
      MemorySize: 256
